import type {
  Asset,
  AssetPage,
  AssetQuery,
  CollectionSummary,
  FilterOptions,
  LibrarySnapshot,
  PackSummary,
  ProjectSummary,
} from "./types";

export const mockPacks: PackSummary[] = [
  {
    id: 1,
    name: "KayKit Medieval Hexagon",
    rootPath: "/home/freeranger/game-assets/kaykit-medieval",
    assetCount: 42,
    lastScannedAt: "2026-08-15T14:30:00Z",
    available: true,
    removedAssetCount: 0,
    missingAssetCount: 0,
  },
  {
    id: 2,
    name: "Kenney Audio Essentials",
    rootPath: "/home/freeranger/game-assets/kenney-audio",
    assetCount: 28,
    lastScannedAt: "2026-08-15T14:30:00Z",
    available: true,
    removedAssetCount: 0,
    missingAssetCount: 0,
  },
  {
    id: 3,
    name: "Quaternius Sci-Fi Modular",
    rootPath: "/home/freeranger/game-assets/quaternius-scifi",
    assetCount: 16,
    lastScannedAt: "2026-08-15T14:30:00Z",
    available: true,
    removedAssetCount: 0,
    missingAssetCount: 0,
  },
];

export const mockProjects: ProjectSummary[] = [
  {
    id: 1,
    name: "DungeonCrawler3D",
    rootPath: "/home/freeranger/GodotProjects/DungeonCrawler3D",
    assetCount: 18,
    available: true,
    lastExportedAt: "2026-08-15T16:00:00Z",
  },
  {
    id: 2,
    name: "SpaceRoguelike",
    rootPath: "/home/freeranger/GodotProjects/SpaceRoguelike",
    assetCount: 8,
    available: true,
    lastExportedAt: "2026-08-14T11:20:00Z",
  },
];

export const mockCollections: CollectionSummary[] = [
  { id: 1, name: "Hero Props", assetCount: 6 },
  { id: 2, name: "Combat SFX", assetCount: 12 },
];

export const mockAssets: Asset[] = [
  {
    id: 1,
    name: "knight_sword_iron",
    packId: 1,
    packName: "KayKit Medieval Hexagon",
    relativePath: "weapons/knight_sword_iron.glb",
    absolutePath: "/home/freeranger/game-assets/kaykit-medieval/weapons/knight_sword_iron.glb",
    extension: "glb",
    assetType: "model",
    fileType: "model",
    usage: null,
    resolution: null,
    sizeBytes: 148500,
    modifiedAt: 1723291200,
    width: null,
    height: null,
    thumbnailPath: null,
    mapRole: null,
    classificationBasis: "extension",
    classificationConfidence: 98,
    manualClassification: false,
    contentHash: "hash1",
    duplicateCount: 0,
    duplicateLocations: [],
    variants: [],
    resources: [],
    tags: ["weapon", "sword", "iron", "melee"],
    collectionIds: [1],
    missing: false,
  },
  {
    id: 2,
    name: "shield_round_wood",
    packId: 1,
    packName: "KayKit Medieval Hexagon",
    relativePath: "armor/shield_round_wood.gltf",
    absolutePath: "/home/freeranger/game-assets/kaykit-medieval/armor/shield_round_wood.gltf",
    extension: "gltf",
    assetType: "model",
    fileType: "model",
    usage: null,
    resolution: null,
    sizeBytes: 94200,
    modifiedAt: 1723291200,
    width: null,
    height: null,
    thumbnailPath: null,
    mapRole: null,
    classificationBasis: "extension",
    classificationConfidence: 95,
    manualClassification: false,
    contentHash: "hash2",
    duplicateCount: 0,
    duplicateLocations: [],
    variants: [],
    resources: [],
    tags: ["armor", "shield", "wood", "defense"],
    collectionIds: [],
    missing: false,
  },
  {
    id: 3,
    name: "stone_wall_brick_albedo",
    packId: 1,
    packName: "KayKit Medieval Hexagon",
    relativePath: "textures/stone_wall_brick_albedo.png",
    absolutePath: "/home/freeranger/game-assets/kaykit-medieval/textures/stone_wall_brick_albedo.png",
    extension: "png",
    assetType: "texture",
    fileType: "image",
    usage: "texture",
    resolution: "2048x2048",
    sizeBytes: 524288,
    modifiedAt: 1723367700,
    width: 2048,
    height: 2048,
    thumbnailPath: null,
    mapRole: "albedo",
    classificationBasis: "filename",
    classificationConfidence: 99,
    manualClassification: false,
    contentHash: "hash3",
    duplicateCount: 0,
    duplicateLocations: [],
    variants: [],
    resources: [],
    tags: ["texture", "stone", "wall", "pbr"],
    collectionIds: [],
    missing: false,
  },
  {
    id: 4,
    name: "sword_clash_impact",
    packId: 2,
    packName: "Kenney Audio Essentials",
    relativePath: "sfx/sword_clash_impact.wav",
    absolutePath: "/home/freeranger/game-assets/kenney-audio/sfx/sword_clash_impact.wav",
    extension: "wav",
    assetType: "audio",
    fileType: "audio",
    usage: null,
    resolution: null,
    sizeBytes: 65536,
    modifiedAt: 1723140000,
    width: null,
    height: null,
    thumbnailPath: null,
    mapRole: null,
    classificationBasis: "extension",
    classificationConfidence: 94,
    manualClassification: false,
    contentHash: "hash4",
    duplicateCount: 0,
    duplicateLocations: [],
    variants: [],
    resources: [],
    tags: ["audio", "sfx", "sword", "impact", "combat"],
    collectionIds: [2],
    missing: false,
  },
  {
    id: 5,
    name: "space_corridor_straight",
    packId: 3,
    packName: "Quaternius Sci-Fi Modular",
    relativePath: "modular/space_corridor_straight.fbx",
    absolutePath: "/home/freeranger/game-assets/quaternius-scifi/modular/space_corridor_straight.fbx",
    extension: "fbx",
    assetType: "model",
    fileType: "model",
    usage: null,
    resolution: null,
    sizeBytes: 348160,
    modifiedAt: 1723472520,
    width: null,
    height: null,
    thumbnailPath: null,
    mapRole: null,
    classificationBasis: "extension",
    classificationConfidence: 96,
    manualClassification: false,
    contentHash: "hash5",
    duplicateCount: 0,
    duplicateLocations: [],
    variants: [],
    resources: [],
    tags: ["scifi", "modular", "corridor", "interior"],
    collectionIds: [],
    missing: false,
  },
  {
    id: 6,
    name: "laser_blast_synth",
    packId: 2,
    packName: "Kenney Audio Essentials",
    relativePath: "sfx/laser_blast_synth.ogg",
    absolutePath: "/home/freeranger/game-assets/kenney-audio/sfx/laser_blast_synth.ogg",
    extension: "ogg",
    assetType: "audio",
    fileType: "audio",
    usage: null,
    resolution: null,
    sizeBytes: 42100,
    modifiedAt: 1723227000,
    width: null,
    height: null,
    thumbnailPath: null,
    mapRole: null,
    classificationBasis: "extension",
    classificationConfidence: 97,
    manualClassification: false,
    contentHash: "hash6",
    duplicateCount: 0,
    duplicateLocations: [],
    variants: [],
    resources: [],
    tags: ["audio", "sfx", "laser", "scifi"],
    collectionIds: [2],
    missing: false,
  },
];

export const mockFilterOptions: FilterOptions = {
  extensions: ["glb", "gltf", "fbx", "png", "jpg", "wav", "ogg"],
  mapRoles: ["albedo", "normal", "roughness", "metallic", "emission"],
  tags: ["weapon", "armor", "texture", "audio", "sfx", "scifi", "stone", "modular"],
};

export const mockSnapshot: LibrarySnapshot = {
  totalAssets: 6,
  missingAssets: 0,
  removedAssets: 0,
  duplicateAssets: 0,
  hashingAssets: false,
  packs: mockPacks,
  collections: mockCollections,
  projects: mockProjects,
  typeCounts: [
    { assetType: "model", count: 3 },
    { assetType: "texture", count: 1 },
    { assetType: "audio", count: 2 },
  ],
};

export function getMockAssetPage(request: AssetQuery): AssetPage {
  let filtered = [...mockAssets];
  if (request.assetType) {
    filtered = filtered.filter((a) => a.assetType === request.assetType);
  }
  if (request.query) {
    const q = request.query.toLowerCase();
    filtered = filtered.filter((a) => a.name.toLowerCase().includes(q) || a.tags.some((t) => t.toLowerCase().includes(q)));
  }
  if (request.packId) {
    filtered = filtered.filter((a) => a.packId === request.packId);
  }
  const offset = request.offset ?? 0;
  const limit = request.limit ?? 50;
  const sliced = filtered.slice(offset, offset + limit);
  return {
    items: sliced,
    total: filtered.length,
    hasMore: offset + limit < filtered.length,
  };
}
